package org.conqueror.db;

import org.conqueror.db.exceptions.db.DBException;
import org.junit.Test;

public class JobDatabaseTest {

	@Test
	public void jobDatabaseTest() throws DBException {
//		JobDatabase jobDB = new JobDatabase("G:\\workspace\\thunder\\data\\db.dat");
//		jobDB.open();
//
//		final TestTableKey k1 = new TestTableKey("k1");
//		final TestTableKey k2 = new TestTableKey("k2");
//		final TestTableKey k3 = new TestTableKey("k3");
//
//		TestTable table = (TestTable) jobDB.openTable(TestTable.class);
//
//		table.insert(k1, new TestTableValue("v1"));
//		table.insert(k2, new TestTableValue("v2"));
//		table.insert(k3, new TestTableValue("v3"));
//
//		System.out.println(table.find(k1).getValue());
//
//		table.update(k1, new TestTableValue("vv1"));
//
//		System.out.println(table.find(k1).getValue());
//		jobDB.commit();
//
//		jobDB.close();
	}

}